// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpNyjLoUqnJOnmr-ctO8ROwLQSqwOIMx8',
    appId: '1:444465712065:web:8359ebda7076b16320fd40',
    messagingSenderId: '444465712065',
    projectId: 'otobook-732a5',
    authDomain: 'otobook-732a5.firebaseapp.com',
    storageBucket: 'otobook-732a5.appspot.com',
    measurementId: 'G-7N76D2RDH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPZ9o9XGaXYoF0s-Q2WAYMdPFIVhS1JFs',
    appId: '1:444465712065:android:7e5619a4a672572620fd40',
    messagingSenderId: '444465712065',
    projectId: 'otobook-732a5',
    storageBucket: 'otobook-732a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxDI-uJMF9ZDw1tebOBW-MS1cKYs3-SF0',
    appId: '1:444465712065:ios:1169ce30eb97bcbf20fd40',
    messagingSenderId: '444465712065',
    projectId: 'otobook-732a5',
    storageBucket: 'otobook-732a5.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxDI-uJMF9ZDw1tebOBW-MS1cKYs3-SF0',
    appId: '1:444465712065:ios:1169ce30eb97bcbf20fd40',
    messagingSenderId: '444465712065',
    projectId: 'otobook-732a5',
    storageBucket: 'otobook-732a5.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpNyjLoUqnJOnmr-ctO8ROwLQSqwOIMx8',
    appId: '1:444465712065:web:b219d5b8f2c0bc8420fd40',
    messagingSenderId: '444465712065',
    projectId: 'otobook-732a5',
    authDomain: 'otobook-732a5.firebaseapp.com',
    storageBucket: 'otobook-732a5.appspot.com',
    measurementId: 'G-3P1XYL8W95',
  );
}
